### ISSUE TITLE
Error to Auth

### ISSUE THREAD

**Issue by maitret** [opauth/live#2]
https://login.live.com/err.srf?lc=3082#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.

My config in https://account.live.com/developers/applications/index:

redirect_uri: https://circleride.herokuapp.com/live/oauth2callback

:cry: :sob:

**Comment by t1mmen** [comment]
In case you're still wondering about this, you'll need to configure your `redirect_uri`, like so:

```
<?php
'Live' => array(
  'client_id' => 'YOUR CLIENT ID',
  'client_secret' => 'YOUR CLIENT SECRET',
  'redirect_uri' => 'https://circleride.herokuapp.com/live/oauth2callback',

)
```
